events { }
http {
    include mime.types;
    types {
        application/wasm wasm;
    }

    server {
        listen 80;

        # Serve files, but if a route isn't found (like /repositories/1), 
        # fall back to index.html so Blazor can handle the routing
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html =404;
        }
    }
}
